version: "3"
services:
  node1:
    container_name: node1
    build: .
    ports:
      - "50000:18443"
      - "50001:18444"
    volumes:
      - ./:/build/parity-bitcoin
    entrypoint: python docker_start.py
  node2:
    container_name: node2
    image: shard-parity-bitcoin_node1 
    ports:
      - "50002:18443"
      - "50003:18444"
    volumes:
      - ./:/build/parity-bitcoin
    entrypoint: python docker_start.py
